/**
 * build-data.js
 *
 * Non-destructive documentation data generator.
 * Reads each package's meta.json and emits the docs' plugin module. Emitting
 * TypeScript rather than JSON means the output is checked against PluginMeta at
 * build time: a renamed field fails the docs build instead of rendering
 * `undefined` on a page. Nothing here writes to a workspace package.
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.resolve(__dirname, "..");
const packagesDir = path.join(rootDir, "packages");
const outputFile = path.join(rootDir, "docs", "app", "data", "generated-plugins.ts");

if (!fs.existsSync(packagesDir)) {
  console.error(`[build-data] Error: packages directory not found at ${packagesDir}`);
  process.exit(1);
}

const packageEntries = fs
  .readdirSync(packagesDir, { withFileTypes: true })
  .filter((entry) => entry.isDirectory() && !entry.name.startsWith("."))
  .map((entry) => entry.name)
  .filter((name) => fs.existsSync(path.join(packagesDir, name, "meta.json")));

const pluginList = packageEntries
  .flatMap((name) => {
    const metaPath = path.join(packagesDir, name, "meta.json");
    const pkgJsonPath = path.join(packagesDir, name, "package.json");

    let metaContent;
    let pkgJson = {};

    try {
      metaContent = JSON.parse(fs.readFileSync(metaPath, "utf-8"));
    } catch (err) {
      console.warn(`[build-data] Warning: Failed to parse ${metaPath}:`, err.message);
      return [];
    }

    if (fs.existsSync(pkgJsonPath)) {
      try {
        pkgJson = JSON.parse(fs.readFileSync(pkgJsonPath, "utf-8"));
      } catch (err) {
        console.warn(`[build-data] Warning: Failed to parse ${pkgJsonPath}:`, err.message);
      }
    }

    const metaArray = Array.isArray(metaContent) ? metaContent : [metaContent];

    // Projected onto the PluginMeta shape rather than spread, so a stray key in
    // a package's meta.json cannot leak into the typed output.
    return metaArray.map((metaData) => {
      const packageName = pkgJson.name || `@supermousejs/${name}`;

      return {
        id: metaData.id,
        name: metaData.name,
        package: metaData.package || packageName,
        description: metaData.description || "",
        code: metaData.code || "",
        icon: metaData.icon || "dot",
        version: metaData.version || pkgJson.version || "0.0.0",
        license: pkgJson.license || "MIT",
        options: metaData.options || [],
        installCommand: `pnpm install ${packageName}`,
        importSnippet: `import { ${metaData.name} } from '${packageName}'`
      };
    });
  })
  .sort((a, b) => a.id.localeCompare(b.id));

const banner = `/**
 * Generated by scripts/build-data.js — do not edit.
 *
 * Reads every package's meta.json and emits a module typed against PluginMeta.
 */

import type { PluginMeta } from "@config/types";

export const GENERATED_PLUGINS: PluginMeta[] = `;

fs.mkdirSync(path.dirname(outputFile), { recursive: true });
fs.writeFileSync(outputFile, `${banner}${JSON.stringify(pluginList, null, 2)};\n`, "utf-8");

console.log(
  `[build-data] Compiled metadata for ${pluginList.length} plugins to docs/app/data/generated-plugins.ts`
);
